sources:
    - ../../Modules/InboxComposer/Sources
    - ../../ProtonPackages/et-protoncore
    - ../../ProtonPackages/proton_app_uniffi
templates:
    - ../
output: ../../Modules/InboxComposer/Sources/Generated
