sources:
    - ../../Modules/InboxContacts/Sources
    - ../../ProtonPackages/et-protoncore
    - ../../ProtonPackages/proton_app_uniffi
templates:
    - ../
output: ../../Modules/InboxContacts/Sources/Generated
